### ISSUE TITLE
Fix OOM

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/apisof.net#1]
The site currently OOMs because it runs out of address space. We're using ASP.NET Core and Antares doesn't support 64 bit yet.

**Comment by jaredpar** [comment]
What other resources are available in the meantime?

**Comment by terrajobst** [comment]
Internally, you can use the API Catalog GUI. Publicly, the only thing we have are the reference assemblies on GitHub.

**Comment by jaredpar** [comment]
Where are the reference assemblies located?

Last night I was porting some desktop code to net standard.  The lack of this data basically brought my coding to a complete halt.  Ended up abandoning my project and moving to other work. 

I didn't want to use any internal tools here because it's not representative of the customer problem.

**Comment by thirkcircus** [comment]
what's happening with this issue?  it seems completely bizarre that you're providing no alternative for non-MS employees.  
this site previously worked (and was useful) - it would be really helpful to know if it's dead forever or will be resurrected.  cheers  :)

**Comment by terrajobst** [comment]
@thirkcircus 

Yes, it shitty. And believe me, even Microsoft employees are yelling at me right now because apisof.net provided a much better XP over what we have. I'll definately want to resurrect it because it's super useful for the work I'm doing day to day -- that's why I wrote it 😄 However, my primary job isn't building tools but to be a PM. Spare time FTW! 😄 

For .NET Standard, you have a low-tech version by browsing the Markdown files I've put here:

https://github.com/dotnet/standard/blob/master/docs/versions.md

(click on the links of the version number and you can see the diff with the previews version as well as the totality of APIs in that version).

**Comment by thirkcircus** [comment]
ok, thanks - that is actually helpful knowing those markdown pages are there.  👍

**Comment by terrajobst** [comment]
Thanks to @glennc I'm now running 64 bit.
