### ISSUE TITLE
Search doesn't work if copy/paste a type

### ISSUE THREAD

**Issue by MagicAndre1981** [terrajobst/apisof.net#11]
When I open the search and copy/paste something like `Microsoft.Win32.SystemEvents` nothing happens. 

![image](https://user-images.githubusercontent.com/8274816/122031755-471ded00-cdcf-11eb-8eb5-399b99b83468.png)

I need to press backspace to remove 1 char and now search works. 

![image](https://user-images.githubusercontent.com/8274816/122031817-5735cc80-cdcf-11eb-8564-e797a6a7613f.png)

**Comment by terrajobst** [comment]
I can't repro this. Does this issue still exist?

**Comment by MagicAndre1981** [comment]
> I can't repro this. Does this issue still exist?

yes, still happens to me with Edge 91 (stable) on Windows 8.1 x64 German.

**Comment by MagicAndre1981** [comment]
Also happens with Edge 91 on Windows 10 . After copy/paste I have to press backspace to delete 1 char to get search working.

**Comment by slang25** [comment]
Same here on macOS & latest stable Chrome.

**Comment by MagicAndre1981** [comment]
Now we have an user who confirmed that is broken on macOS, can you check this please @terrajobst  ? Which OS/Browser do you use that it works for you? I also tested it on my Pixel3a with Android 11 and Brave and shows the same issue. Only after removing 1 char the search starts

**Comment by terrajobst** [comment]
I believe I fixed it

**Comment by MagicAndre1981** [comment]
> I believe I fixed it

now it works for me. Thanks

**Comment by slang25** [comment]
Thanks for the fix!

What's awesome as well is that after landing on the main page, I can hit `/` to bring up the search panel, paste in my type and hit enter. It's such a smooth workflow now 😄  Thanks @terrajobst
