### ISSUE TITLE
A11y_api-catalog_.NET API Catalog _ Zooming: At 200% zooming, when user expands hamburger menu focus is going outside the expanded list

### ISSUE THREAD

**Issue by SaisreeDandamudi** [terrajobst/apisof.net#12]
[Check out Accessibility Insights] - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:** 
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.4.4; #C+E-H; #api-catalog; #Resize; #Edge; #Chrome; #Benchmark; #A11ySev2;

**Environment Details:**
URL: https://apisof.net/

**Browser:**
Microsoft Edge 44.18362.267.0
Chrome Version 76.0.3809.100

**Re-pro Steps:**
1.	Hit the URL
2.	Change the browser zooming to 200%
3.	Verify whether focus order is correct when user expands hamburger button

**Actual Result:**
At 200% zooming, when user expands hamburger menu focus is going outside the expanded list

**Expected result:**
When user expands a button or drop down focus should rotate inside the expanded list until the user collapse the expanded list

**User Impact:**
Users will get confused if the keyboard focus comes out of the hamburger menu item

[12.focus order issue in hamburger menu.pptx](https://github.com/terrajobst/apisof.net/files/3533790/12.focus.order.issue.in.hamburger.menu.pptx)

**Comment by terrajobst** [comment]
The web site no longer exists.
