### ISSUE TITLE
A11y_api-catalog_System.Activities.Debugger_High Contrast: Graph is not visible in high contrast black mode

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#13]
[Check out Accessibility Insights ](https://www.1eswiki.com/wiki/Accessibility_Insights)- Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.4.3; #HighContrast; #C+E-H; #api-catalog; #Edge; #A11ySev2; #NonBenchmark;

**Environment Details:**
URL: https://apisof.net/

**Browser:**
Microsoft Edge 44.18362.267.0

**Repro steps:**
1)Turn on High contrast black mode
2) Hit the URL : "http://apisof.net" and press enter
3)Tab till "Browse" button and press enter
4)Tab till "System.Activities.Debugger" and press enter
5)Check whether 'Graph' is visible in high contrast black mode 

**Actual Result:**
Graph is not visible in high contrast black mode

**Expected Result:**
Graph should be visible in high contrast black mode

**User Impact:**
Low vision users will miss the content if graph is not visible in high contrast black mode

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a73546c7-765f-489c-b18f-afb659fe99e6}

[Graph not visible in high contrast black mode.pptx](https://github.com/terrajobst/apisof.net/files/3533276/Graph.not.visible.in.high.contrast.black.mode.pptx)

**Comment by terrajobst** [comment]
The web site no longer exists.
