### ISSUE TITLE
A11y_api-catalog_System.Activities.Debugger_Zooming: Focus is not visible on Hamburger menu when zoomed to 200% 

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#15]
[Check out Accessibility Insights](https://www.1eswiki.com/wiki/Accessibility_Insights) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.4.4; #MAS2.4.7; #Keyboard; #C+E-H; #api-catalog; #Edge; #Chrome; #A11ySev2; #NonBenchmark;

**Environment Details:**
URL: https://apisof.net/

**Browser:**
Microsoft Edge 44.18362.267.0
Chrome Version 76.0.3809.100

**Repro steps:**
1)Hit the URL : "http://apisof.net" and press enter
2)Tab till "Browse" button and press enter
3)Tab till "System.Activities.Debugger" and press enter
4)Resize upto 200%
5)Tab till 'Hamburger' menu 
6)Check whether focus is visible on 'Hamburger' menu or not

**Actual Result:**
Focus is not visible on Hamburger menu when zoomed to 200% 

**Expected Result:**
Focus should be visible on Hamburger menu when zoomed to 200% 

**User Impact:**
Users with low vision will find difficulty in operating the application if focus is not visible on the control

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b69e5ccc-dde2-4406-b550-4deb38648f6d}

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={3b98b04f-4fab-4d3e-81af-a0906a34849c}

[Focus not visible on hamburger menu.pptx](https://github.com/terrajobst/apisof.net/files/3533287/Focus.not.visible.on.hamburger.menu.pptx)

**Comment by terrajobst** [comment]
The web site no longer exists.
