### ISSUE TITLE
Types that appear in .NET Core 3.1 and .NET 5+ only listed as .NET Core 3.1

### ISSUE THREAD

**Issue by AArnott** [terrajobst/apisof.net#15]
One example: https://apisof.net/catalog/f7b66281-c151-64d2-5f22-ed17ccd38a0f

**Comment by terrajobst** [comment]
That's not actually a false positive; we did make a breaking change in .NET Core 3.1 and removed this type and a few others:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#change-description

I think the reason why .NET Core 3.1 is listed is a mistake; it should only list .NET Core 3.0. I think that's an issue with the copy of .NET Core 3.1 I've snapshotted -- it was a breaking change that we did late in 3.1.

**Comment by AArnott** [comment]
I don't understand. You say you removed the type in .NET Core 3.1, but apisof.net shows that it _is_ present in .NET Core 3.1. 
![image](https://user-images.githubusercontent.com/3548/161442724-759f4fe8-ebae-4262-b540-8fd2c735ed03.png)

I thought the `MainMenu` type was surely still in .NET because the C# completion list offered it while I targeted .NET 6:
![image](https://user-images.githubusercontent.com/3548/161442826-529f8fd1-318b-4c1f-b46b-8d836689cc05.png)

But I guess maybe that's a bug in the C# language service. Upon accepting that completion, it doesn't compile.

**Comment by terrajobst** [comment]
> I don't understand. You say you removed the type in .NET Core 3.1, but apisof.net shows that it _is_ present in .NET Core 3.1.

Yeah, that's a bug in apisof.net. The archived version of .NET Core 3.1 was taken before we made that breaking change. I just uploaded the latest version of .NET Core 3.1 and kicked off another indexer run. In an hour or so it should show as being only available in .NET Core 3.0 and no later versions.

> But I guess maybe that's a bug in the C# language service. Upon accepting that completion, it doesn't compile.

Interesting. Yeah, that does sound like a bug in the language service.

**Comment by terrajobst** [comment]
@AArnott is the project with the suggestion multi-targeted? If so, it's probably related to the other bug you reported regarding COM where the language service does an aggregation of all targets.

**Comment by AArnott** [comment]
No, I'm not multi-targeting in that project.

**Comment by terrajobst** [comment]
That's very odd. Might be the independent type recommender service that can also suggest NuGet packages. They probably can't handle breaking changes in API surface and assume that if version X had a type, that version Y > X also has that type, which is generally a reasonable assumption.

**Comment by AArnott** [comment]
I'll wrap up a repro and file a bug against Roslyn in case they can fix it.
