### ISSUE TITLE
What is the "package provided API"?

### ISSUE THREAD

**Issue by Smartisa** [terrajobst/apisof.net#16]
Please forgive my stupidity. After comparing some packages, I don't know what is the "package provided API" ?

**Comment by terrajobst** [comment]
We have the notion of platform APIs and package APIs. Basically, a platform provided API is part of the framework whereas a package provided API requires referencing a package. The challenge is that the answer might differ based on the framework version. For example, consider `System.Text.Json`:

![image](https://user-images.githubusercontent.com/5169960/161016884-1ddca937-a822-4ef2-9224-78cd0d2bc868.png)

Starting with .NET 5, the API is platform provided. However, we also provided a NuGet package via .NET Standard 2.0. If you click on any platform version, e.g. .NET Framework 4.8, you'll see what happens. Here you can see that the API is coming from a NuGet package named `System.Text.Json` and that you get a binary that was built for .NET Framework 4.6.2.

![image](https://user-images.githubusercontent.com/5169960/161017186-fc3f53ce-8863-47fc-99d0-0d7b032b1229.png)

If you instead click on the .NET 5.0 version, you'll see that there is no package involved:

![image](https://user-images.githubusercontent.com/5169960/161017454-f4511b1b-8029-47bb-9424-634ab3121dc3.png)
