### ISSUE TITLE
.Net Standard 1.x types that are not referenced from NETStandard.Library are not listed

### ISSUE THREAD

**Issue by svick** [terrajobst/apisof.net#2]
[The page for the `XmlNode` type](https://apisof.net/catalog/System.Xml.XmlNode) does not list .Net Standard 1.3 among the available platforms, even though this type is available in .Net Standard 1.3 libraries.

As far as I can tell, this is because the package that contains this type (`System.Xml.XmlDocument`)  is not referenced from the `NETStandard.Library` package.

I think it would be useful to include .Net Standard 1.x as a platform even for types whose packages have to be explicitly referenced when writing a .Net Standard 1.x library. Though possibly there could be some differentiation between the two cases.

**Comment by terrajobst** [comment]
[Fixed now](https://apisof.net/catalog/b6495273-244d-5148-81c6-34c94a1d9a56):

![image](https://user-images.githubusercontent.com/5169960/120551908-6ff3ba80-c3ab-11eb-9f41-8644a321f0c2.png)
