### ISSUE TITLE
MAS3.1.1: <html> element must have a lang attribute (html)

### ISSUE THREAD

**Issue by SaisreeDandamudi** [terrajobst/apisof.net#20]
**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS3.1.1; #C+E-H; #api-catalog; #Benchmark; #A11ySev2;

#### Issue
`<html> element must have a lang attribute` ([html-has-lang](https://dequeuniversity.com/rules/axe/3.2/html-has-lang?application=msftAI))
#### Target application
[Home - .NET API Catalog](https://apisof.net/)
#### Element path
html
#### Snippet
`<html>`
#### How to fix
    Fix any of the following:
      The <html> element does not have a lang attribute
#### Environment
Chrome version 76.0.3809.100
This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).
![html lang issue](https://user-images.githubusercontent.com/51435580/63583700-23b1fe80-c5b9-11e9-8adf-231b82a5d0b8.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
