### ISSUE TITLE
A11y_api-catalog_System.Activities.Debugger_Keyboard: After navigating to all controls in any of the Catalogs, it is taking one extra tab to move to start of the page

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#21]
[Check out Accessibility Insights](https://www.1eswiki.com/wiki/Accessibility_Insights) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS2.4.3; #Keyboard; #C+E-H; #api-catalog; #Chrome; #A11ySev3; #NonBenchmark;

**Environment Details:**
URL: https://apisof.net/

**Browser:**
Chrome Version 76.0.3809.100

**Repro steps:**
1)Hit the URL : "http://apisof.net" and press enter
2)Tab till "Browse" button and press enter
3)Tab till "System.Activities.Debugger" and press enter
4)Check whether it is taking one extra key tab to move to start of the page after navigating to all controls 

**Actual Result:**
After navigating to all controls in any of the Catalogs, it is taking one extra tab to move to start of the page

**Expected Result:**
After navigating to all controls in any of the Catalog, it should not take one extra tab to move to start of the page

**User Impact:**
Keyboard only users will find difficulty if it is taking one extra tab to move to next control

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

[Taking one extra tab to navigate to next control.pptx](https://github.com/terrajobst/apisof.net/files/3533873/Taking.one.extra.tab.to.navigate.to.next.control.pptx)

**Comment by terrajobst** [comment]
The web site no longer exists.
