### ISSUE TITLE
MAS 2.4.1: Frames must have title attribute (iframe)

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#23]
**GitHubTags:**

#A11yTCS; #A11yMAS; #A11yAuto; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS2.4.1; #C+E-H; #api-catalog; #A11ySev2; #NonBenchmark;

#### Issue
`Frames must have title attribute` ([frame-title](https://dequeuniversity.com/rules/axe/3.2/frame-title?application=msftAI))
#### Target application
[System.Activities.Debugger - .NET API Catalog](https://apisof.net/catalog/System.Activities.Debugger)
#### Element path
iframe
#### Snippet
`<iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>`
#### How to fix
    Fix any of the following:
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Element has no title attribute or the title attribute is empty
      Element's default semantics were not overridden with role="presentation"
      Element's default semantics were not overridden with role="none"
#### Environment
Chrome version 76.0.3809.100
This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

![Keros bug  MAS2 4 1](https://user-images.githubusercontent.com/51435266/63583964-a3d86400-c5b9-11e9-840d-a981a2d72f09.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
