### ISSUE TITLE
MAS 1.1.1: Images must have alternate text (img[src$="Namespace_16x\.svg"])

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#24]
**GitHubTags:**
#A11yTCS; #A11yMAS; #A11yAuto; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.1.1; #C+E-H; #api-catalog; #A11ySev2; #Benchmark;

#### Issue
`Images must have alternate text` ([image-alt](https://dequeuniversity.com/rules/axe/3.2/image-alt?application=msftAI))
#### Target application
[System.Activities.Debugger - .NET API Catalog](https://apisof.net/catalog/System.Activities.Debugger)
#### Element path
.active > img[src$="Namespace_16x\.svg"]
#### Snippet
`<img width="16" height="16" src="/images/api/Namespace_16x.svg">`
#### How to fix
    Fix any of the following:
      Element does not have an alt attribute
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Element has no title attribute or the title attribute is empty
      Element's default semantics were not overridden with role="presentation"
      Element's default semantics were not overridden with role="none"
#### Environment
Chrome version 76.0.3809.100
This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

![Keros bug  MAS1 1 1](https://user-images.githubusercontent.com/51435266/63584231-23663300-c5ba-11e9-8b5c-732317c5f05e.png)

![Keros bug_Search  MAS1 1 1](https://user-images.githubusercontent.com/51435266/63586594-434c2580-c5bf-11e9-91d8-771e8044648c.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
