### ISSUE TITLE
MAS2.4.1: Page must have means to bypass repeated blocks (html)

### ISSUE THREAD

**Issue by SaisreeDandamudi** [terrajobst/apisof.net#25]
**GitHubTags:** 
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS2.4.1; #C+E-H; #api-catalog; #Benchmark; #A11ySev2;

#### Issue
`Page must have means to bypass repeated blocks` ([bypass](https://dequeuniversity.com/rules/axe/3.2/bypass?application=msftAI))
#### Target application
[Catalog - .NET API Catalog](https://apisof.net/catalog)
#### Element path
html
#### Snippet
`<html>`
#### How to fix
    Fix any of the following:
      No valid skip link found
      Page does not have a header
      Page does not have a landmark region
#### Environment
Chrome version 76.0.3809.100
This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).
![Bypass blocks Accessibility issue](https://user-images.githubusercontent.com/51435580/63586241-8e196d80-c5be-11e9-9e8d-89f1a7d533af.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
