### ISSUE TITLE
MAS 1.3.1, MAS 3.3.2: Form elements must have labels (input)

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#26]
**GitHubTags:**
#A11yTCS; #A11yMAS; #A11yAuto; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.3.1; #MAS3.3.2; #C+E-H; #api-catalog; #A11ySev2; #Benchmark;

#### Issue
`Form elements must have labels` ([label](https://dequeuniversity.com/rules/axe/3.2/label?application=msftAI))
#### Target application
[System.Activities.Debugger - .NET API Catalog](https://apisof.net/catalog/System.Activities.Debugger)
#### Element path
input
#### Snippet
`<input class="search-box au-target" placeholder="Enter term e.g. 'str.len'" value.bind="term" focus.one-way="isVisible" input.trigger="search($event)" au-target-id="2">`
#### How to fix
    Fix any of the following:
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Form element does not have an implicit (wrapped) <label>
      Form element does not have an explicit <label>
      Element has no title attribute or the title attribute is empty
#### Environment
Chrome version 76.0.3809.100
This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

![Keros bug  MAS1 3 1, MAS3 3 2](https://user-images.githubusercontent.com/51435266/63586232-88238c80-c5be-11e9-9ddb-7c798cbd2be3.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
