### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by mj1856** [terrajobst/apisof.net#3]
Viewing the site in Chrome gives an https error because the cert was issued by StartCom, which is generally distrusted.

https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

Would you please use a cert from a different CA?  Thanks.

**Comment by jeremyVignelles** [comment]
Let's encrypt is a free, recognized and widely used CA. It also have a huge community for automatic certificate requests/renewal.

Would you mind using this instead of your CA? This would be great for user experience

**Comment by jamesqo** [comment]
Yeah, I'm also getting this error every time I try to go to the site. Would be nice if this were fixed :smile:

**Comment by dasMulli** [comment]
@terrajobst any plan of updating the cert? I've been posting links to it on StackOverflow like crazy and everyone probably thinks I just want to steal their credit card info 😂

**Comment by danmosemsft** [comment]
@terrajobst ?

**Comment by jeremyVignelles** [comment]
Chrome now tells me the certificate has been revoked. That's too bad, I can't use this site anymore. Please make it HTTP or take a certificate at letsencrypt...

**Comment by terrajobst** [comment]
This has been fixed as of last week.
