### ISSUE TITLE
Usage doc feedback

### ISSUE THREAD

**Issue by AArnott** [terrajobst/apisof.net#30]
From the usage doc:

```
usage: apisofdotnet check-apis [OPTIONS]+
 -t, --target=target        The target framework to check availability for
      --obs, --obsoletion    Include information about obsoleted APIs
  -p, --platform=platform    The OS platform to check availability for
  -o, --out=filename         The filename of the report
```

As you have -t already, and your list-frameworks command shows Windows-specific TFMs to pick from, when would I use the -p parameter?

Should I add --obs in order to flag uses of obsolete APIs to the output? Are these obsolete-but-working APIs or APIs that exist but will definitely throw on .NET?

The -o parameter doc doesn't indicate which file extension would make the most sense to use for the output filename. Since you produce csv formatted files, perhaps mention that in your usage doc.

There is nothing at all in the usage doc to show how/where I specify which assemblies to scan. I can only guess that you'll scan the current directory, which isn't what I wanted (although I can adapt). Is it recursive? Do you scan .exe's as well as .dll's? More docs would be great.

**Comment by terrajobst** [comment]
> As you have -t already, and your list-frameworks command shows Windows-specific TFMs to pick from, when would I use the -p parameter?

Not all platforms have TFMs. Also, we have APIs in `netX.Y` that don't work on all platforms. For example, some parts of crypto and threading don't work in web assembly (`browser`). Basically, this exposes the what the [platform compatibility analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer) does (via the `[SupportedOSPlatform]`/`[UnsupportedOSPlatform]` attributes).
