### ISSUE TITLE
Generated csv should have consistent numbers of fields per record

### ISSUE THREAD

**Issue by AArnott** [terrajobst/apisof.net#31]
Parsing the output CSV programmatically is a challenge. There are quotes to consider. So I pulled [the most popular CSV reader](https://github.com/phatcher/CsvReader) off the shelf, and it immediately rejected the csv. I think it's because you have an inconsistent number of fields per record. 
You should have 6 columns on every line, per the header. But many lines have only 3 fields:

```
some.dll,Not a valid .NET assembly,
```

**Comment by AArnott** [comment]
Indeed. By adding 3 more commas to every line such as the one in the description, I can now parse the file with a CSV reader.

**Comment by terrajobst** [comment]
Oopsy. Fixed with 8123b4959cea60258dbbc0c25419fa1de6c2b19d.
