### ISSUE TITLE
False positives for net6.0-windows

### ISSUE THREAD

**Issue by AArnott** [terrajobst/apisof.net#32]
- [ ] A bunch of APIs are reported missing under `Microsoft.FSharp.Core`. Are F# APIs really not available under net6.0-windows?
- [ ] System.Type.Name.get

**Comment by terrajobst** [comment]
> A bunch of APIs are reported missing under `Microsoft.FSharp.Core`. Are F# APIs really not available under net6.0-windows?

Looks like I don't index FSharp.* packages. I have fixed that with 0d7362301da8d7fcf36ad5dc3ba178705aaf9713. After tomorrow, we should know about them.

> System.Type.Name.get

Ah yes. Basically, that's another instance of the reflection issue I tried to fix with 5ec1950469509469ed07137c93f89e090d2e5300. Looks like I missed `Type.Name` which on .NET Framework is inherited from `MemberInfo`. In .NET Core v1 we made `System.Type` not inherit from `MemberInfo` and instead added `TypeInfo`. I believe I have fixed that in d1b0c07771d75534c81ce41d0d8c7a4412b548a1.
