### ISSUE TITLE
For an M$ product... very disappointing. Issue #1: .Net upgrade planner crashes

### ISSUE THREAD

**Issue by schittli** [terrajobst/apisof.net#39]
### Version
0.1.11-beta (767890aaabc54c4a13e4bd90eeb955c21b5836af)

Good evening

I hope you don't spend your free time developing the very important tool .NET Upgrade Planner. Therefore, I assume that it is an M$ tool. And it is very disappointing.

About a decade ago, we (as an M$ Gold Partner!) switched the platform and went to Java. C# is great, but the tools offered by M$ were embarrassing.

About 2 weeks ago we installed Visual Studio Enterprise 2022 again to see how M$ has evolved and we just compare it to the IntelliJ Community Edition.

It's a shame that M$ developers have to pay for Visual Studio: The IDE crashes, has lousy usability, and most important: the problems we had a decade ago are still unsolved.

We would have expected a tool like .NET Upgrade Planner to be a standard Visual Studio feature by now. And, of course, a mature product.

Far from it: .NET Upgrade Planner not only crashes on the first test, but it is also programmed in such a way that the framework does not even catch the exception and provides information for the developers and users. It just crashes and disappears.

As a developer, I would be embarrassed if my customers had to write me this proposal:

- please catch exceptions
- please allow exceptions to be sent to GitHub
- please display information to the user so that they can interpret the error and perhaps derive a workaround.

It's a shame that those basic functions are not part of the framework / an activatable component so it just works.

That's the next shame:
Developers of open-source projects rarely miss the opportunity to include short, useful information about the project.
For .NET Upgrade Planner M$ really doesn't manage to provide more than just a screenshot?

Really a pity if M$ is not interested in not solving decades-old problems of developers supporting the M$ platforms.

I think we'll look at M$ Developer tools again in another decade. Probably the tool will still not work, but at least it won't crash anymore... right? 😢 

Kind regards,
Thomas

**Comment by terrajobst** [comment]
1. It's an official Microsoft product, it's a prototype that I built
2. I'm sorry that it crashes for you but since you provided no details, I'm not sure what to do with that.
