### ISSUE TITLE
apisof.net website not working

### ISSUE THREAD

**Issue by doggy8088** [terrajobst/apisof.net#4]
Using my normal Google Chrome browser is bad.
![image](https://user-images.githubusercontent.com/88981/35181605-0b31f5e0-fe00-11e7-8daf-c40fd9763977.png)

Use In-Private browsing, it's ok.
![image](https://user-images.githubusercontent.com/88981/35181608-1a0a06de-fe00-11e7-9235-3a829ace32ae.png)

I don't know what's happening.  Maybe some of your servers are down in a web farm.

**Comment by terrajobst** [comment]
Should be fixed now; it's a new backend.
