### ISSUE TITLE
Show Xamarin.Android & Xamarin.iOS?

### ISSUE THREAD

**Issue by jonpryor** [terrajobst/apisof.net#6]
Would it be possible for the APIs in Xamarin.Android (`Mono.Android.dll`) and Xamarin.iOS (`Xamarin.iOS.dll`), among others, be added to apisof.net?

**Comment by terrajobst** [comment]
Should [be fixed now](https://localhost:44340/catalog/3e108182-236f-5ccb-b5ee-e91a6d09cea0):

![image](https://user-images.githubusercontent.com/5169960/120551800-476bc080-c3ab-11eb-9c4f-7643695f0af6.png)
