### ISSUE TITLE
A11y_api-catalog_Search_Screen Reader: When keyboard focus lands on search suggestion list items, Narrator not reading anything

### ISSUE THREAD

**Issue by Amulya-95** [terrajobst/apisof.net#8]
[Check out Accessibility Insights](https://www.1eswiki.com/wiki/Accessibility_Insights) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS1.3.1; #ScreenReader; #C+E-H; #api-catalog; #Edge; #Chrome; #Narrator; #NVDA; #A11ySev1; #Benchmark;

**Environment Details:**
URL: https://apisof.net/

**Browser:**
Microsoft Edge 44.18362.267.0
Chrome Version 76.0.3809.100

**Repro steps:**

1)Turn on the screen reader (Narrator/NVDA)
2)Hit the URL : "http://apisof.net" and press enter
3)Tab till "Search" and press enter or else press "Slash" key
4)Tab till search field and type the content which you want to search
5)Navigate to search suggestion list items using arrow keys 
6)Verify whether screen reader is reading the list items or not 

**Actual Result:**
When keyboard focus lands on search suggestion list narrator not reading anything. NVDA is just reading the content present in search field.
Example: If user type "Str" in search field suggestion list items will be displayed and when user navigate to list items using arrow key then NVDA is just read as "Str" instead of reading the content displayed

**Expected Result:**
When keyboard focus lands on search suggestion list narrator should read the list item

**User Impact:**
Visually disabled users will feel difficult and will miss the content if narrator is not reading the content present

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

[Narrator not reading the suggestion list.pptx](https://github.com/terrajobst/apisof.net/files/3533207/Narrator.not.reading.the.suggestion.list.pptx)

![NVDA not reading the suggestion list item](https://user-images.githubusercontent.com/51435266/63573464-0a05bc80-c5a3-11e9-9216-3683f335b70d.png)

**Comment by terrajobst** [comment]
The web site no longer exists.
