### ISSUE TITLE
A11y_api-catalog_.NET API Catalog _ Keyboard: Focus is not clearly visible on “Browse” and “Search” buttons

### ISSUE THREAD

**Issue by SaisreeDandamudi** [terrajobst/apisof.net#9]
[Check out Accessibility Insights] - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:**
#A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_api-catalog; #MAS2.4.7; #Keyboard; #C+E-H; #api-catalog; #Edge; #Chrome; #Benchmark; #A11ySev2;

**Environment Details:**
URL: https://apisof.net/

Browser:
Microsoft Edge 44.18362.267.0
Chrome Version 76.0.3809.100

**Re-pro Steps:**
1.	Hit the [URL](https://apisof.net/)
2.	Verify whether keyboard focus is clearly visible on “Browse” button and “Search” button

**Actual Result:**
Focus is not clearly visible on “Browse” and “Search” buttons

**Expected result:**
Focus should be clearly visible on “Browse” and “Search” buttons

**User Impact:**
Users will not get to know where the keyboard focus is, if keyboard focus is not clearly visible on the controls

[9.focus is not clearly visible on browse and search controls.pptx](https://github.com/terrajobst/apisof.net/files/3533204/9.focus.is.not.clearly.visible.on.browse.and.search.controls.pptx)

**Comment by terrajobst** [comment]
The web site no longer exists.
